[package]
name = "native-launcher"
version = "0.1.0"
edition = "2021"
workspace = "../.."

[dependencies]
bevy-rogue = { package = "bevy-rogue", path = "../.." }
bevy = "0.8.1"
image = "0.24.4"
winit = "0.26.1"